name: Bug Report
description: File a reproducible bug to help us improve the mod
title: "[Bug]: "
labels: ["bug"]
assignees:
  - tajemniktv

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: What happened?
    validations:
      required: true
